Module4 task2
htmlacademy-ecmascript/1783103-big-trip-21 pull request #7
Opened 2023-09-14 15:29 UTC by vostrStudy

1. Добавлены исправления module4-task1
2. добавлены моки для работы с фильтрами. Добавлено отображения кол-ва точек маршрута в соответствии с фильтрами. 
3. не добавлено сообщение о пустой странице, когда нет соответствующих фильтрам точек маршрута. не знаю как его отображать.
4. не знаю что делать с фильтрами дальше. добавляю обработчик по клику и дальше в презентер?
5. добавлены функции генерации случайной даты через геттеры. Не знаю так правильно? (модуль points.js ,строка 41-48)

2023-09-16 20:13 UTC, arcticneko commented
**1.** Здорово! По поводу закрепления версий написал отдельный коммент
**3.** https://up.htmlacademy.ru/ecmascript/21/module/4/item/18
33м 7с, строка 32
можно сделать как в ретро, создать компонент для пустого списка и отрисовывать там верстку наподобие "в вашем списке пока нет точек маршрута".
**4.** пока этого достаточно
**5.** а зачем там геттеры? это простой объект с данными, ему не нужны геттеры. пока оставь, в следу ДЗ все равно будем рефакторить этот кусок

так же проверь пожалуйста, почему у тебя падает сборка:
![image](https://github.com/htmlacademy-ecmascript/1783103-big-trip-21/assets/65240326/7a5b3392-9ddc-4005-b139-808735a8786b)

2023-09-16 20:19 UTC, arcticneko requested changes

2023-09-16 20:19 UTC, arcticneko commented on package.json
> +    "style-loader": "^3.3.2"
https://github.com/htmlacademy-ecmascript/1783103-big-trip-21/pull/6#discussion_r1324966632
согласно требованиям зависимости должны быть без крышечек, как в файле requirements.md
нужно убрать "крышечки ^"

подробнее про флаги -E и -DE можно почитать тут:
https://htmlacademy.ru/blog/js/package-update

2023-09-16 21:00 UTC, arcticneko commented on src/template/filter-template.js
> +  </div>
строка с {count} лишняя, у нас нет каунтеров напротив фильтров
поправь, пожалуйста

2023-09-19 00:22 UTC, vostrStudy commented
Добавлены исправления.
1. добавлены фильтры
2. добавлена работа с сортировкой. возникла проблема с отрисовкой сортировки в презентере

2023-09-21 11:19 UTC, merged