Module5 task1
htmlacademy-ecmascript/1783103-big-trip-21 pull request #8
Opened 2023-09-19 13:51 UTC by vostrStudy

1. добавлены новые презентеры (filter-presenter, point-presenter)
2. добавлена обработка фильтров
3. добавлен метод клака обработки звездочки
4. добавлена функция изменения данных
5. добавлена перересока фильтров. Не могу найти где делать рендер класса SortView. раньше отрисовывала в main.js. Нужна помошью файл event-presenter.. строка 56
6. так же проблема с открытием только одной формы

2023-09-20 14:06 UTC, vostrStudy commented
1.добавлены новые презентеры (filter-presenter, point-presenter)
2.добавлена обработка фильтров
3.добавлен метод клика обработки звездочки
4.добавлена функция изменения данных
5.добавлена перерисовка фильтров. Проблема. не переключает сортировку по клику
6. Проблема с открытием только одной формы. возможно forEach(#handleModeChange) event-presenter, line 58 возвращает обработку только на последнюю точку. с ней отрисовка только одной формы работает

2023-09-20 20:32 UTC, arcticneko requested changes

2023-09-20 20:32 UTC, arcticneko commented on src/view/radio-list-view.js
> +  _handleItemsChange;
```#handleItemsChange```

2023-09-20 20:32 UTC, arcticneko commented on src/view/radio-list-view.js
> +    this.handleItemChange?.(evt.target.dataset.item);
```this._handleItemsChange?.(evt.target.dataset.item);```

2023-09-20 20:32 UTC, arcticneko commented on src/presenter/event-presenter.js
> +    this.#points = sort[SortType.DAY](this.#eventModel.get());
```this.#points = sort[this.#currentSortType](this.#eventModel.get());```

2023-09-20 20:32 UTC, arcticneko commented on src/view/radio-list-view.js
> +    this._handleItemsChange = onItemChange;
почему ```_handleItemsChange``` а не ```#handleItemsChange``` ?

2023-09-20 20:32 UTC, arcticneko commented on src/template/sort-template.js
> +  <label class="trip-sort__btn" for="sort-${type} ">${type} </label>
в ```src/view/radio-list-view.js``` ожидается data-item при клике на label, но здесь оно не навешивается

2023-09-20 20:32 UTC, arcticneko commented on src/view/radio-list-view.js
> +    this.element.addEventListener('change', this.#itemChangeHandler);
```this.element.addEventListener('click', this._handleItemsChange);```

2023-09-20 20:32 UTC, arcticneko commented
> 1.добавлены новые презентеры (filter-presenter, point-presenter) 2.добавлена обработка фильтров 3.добавлен метод клика обработки звездочки 4.добавлена функция изменения данных 5.добавлена перерисовка фильтров. Проблема. не переключает сортировку по клику 6. Проблема с открытием только одной формы. возможно forEach(#handleModeChange) event-presenter, line 58 возвращает обработку только на последнюю точку. с ней отрисовка только одной формы работает

5 расписал комментариями в коде
6. в ```src/utils/const.js``` UUID создается один раз, из-за чего у всех точек один и тот же id. из-за этого перезатираются все точки в мапе (так как запись постоянно по одному ключу UUID) и остается одна точка:
![image](https://github.com/htmlacademy-ecmascript/1783103-big-trip-21/assets/65240326/022e4472-b341-4db0-894a-a8b0cb072e59)

2023-09-21 04:24 UTC, vostrStudy commented on src/view/radio-list-view.js
> +    this._handleItemsChange = onItemChange;
В ретроспективе советовали делать защищенный оба и _items и _handleItemsChange. чтобы они были доступны из дочерних классов. Я в итоге оставила их пока защищенными а не приватными

2023-09-21 04:25 UTC, vostrStudy commented
Вадим большое спасибо! 
Все поправила все работает. Прими пожалуйста.

Главной ошибкой в итоге была опечатка this._handleItem**s**Change?.(evt.target.dataset.item);

2023-09-21 11:14 UTC, arcticneko commented on src/view/radio-list-view.js
> +    this._handleItemsChange = onItemChange;
на твоей совести будет уточнить этот вопрос.
очень странно что здесь ```_handleItemsChange``` в то время как во всем проекте мы используем формат ```#handleItemsChange```

2023-09-21 11:19 UTC, arcticneko approved these changes

2023-09-21 11:19 UTC, merged